domain-needed
bogus-priv
localise-queries
stop-dns-rebind
rebind-localhost-ok

local=/lan/
domain=lan
expand-hosts

cache-size=1000
dhcp-authoritative
read-ethers

user=dnsmasq
group=dnsmasq
pid-file=

dhcp-leasefile=/tmp/dhcp.leases
resolv-file=/tmp/resolv.conf

interface=br0
bind-dynamic

dhcp-range=192.168.1.100,192.168.1.249,255.255.255.0,12h

edns-packet-max=1232

conf-file=/usr/share/dnsmasq/rfc6761.conf
conf-file=/usr/share/dnsmasq/dhcpbogushostname.conf
dhcp-ignore-names=tag:dhcp_bogus_hostname
