#!/bin/sh

SVSRC=/etc/sv
SVRUN=/var/sv
SVDIR=/var/service
SVLIST=/etc/services.enabled

mkdir -p "$SVRUN" "$SVDIR"

[ -f "$SVLIST" ] || exit 0

while read -r service; do
	case "$service" in
		''|\#*) continue ;;
	esac

	[ -x "$SVSRC/$service/run" ] || {
		echo "service_setup: invalid service: $service" >&2
		continue
	}

	cp -a "$SVSRC/$service" "$SVRUN/$service"
	ln -s "../sv/$service" "$SVDIR/$service"
done < "$SVLIST"

exit 0
