#!/bin/sh

. /lib/functions.sh

include /lib/upgrade

v "Performing system upgrade..."

if type platform_do_upgrade >/dev/null 2>&1; then
	platform_do_upgrade "$IMAGE"
else
	default_do_upgrade "$IMAGE"
fi

if [ -n "$UPGRADE_BACKUP" ] &&
   type platform_copy_config >/dev/null 2>&1; then
	platform_copy_config
fi

v "Upgrade completed"

sync
umount -a

v "Rebooting system..."
reboot -f

# Fallback in case reboot does not return as expected.
sleep 5
echo b > /proc/sysrq-trigger 2>/dev/null
