interface=wlan0
driver=nl80211

ssid=RT3052

hw_mode=g
channel=11
country_code=NL
ieee80211d=1

ieee80211n=1
wmm_enabled=1
ht_capab=[SHORT-GI-20]

wpa=2
wpa_passphrase=test1234
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
