table ip nat {
	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		oifname { "wan", "wan.10" }  masquerade
	}
}

table ip fw {
	flowtable f {
		hook ingress priority 0;
		devices = { lan1, lan2, lan3, lan4 , wan };
		flags offload;
	}

	chain input {
		type filter hook input priority 0; policy drop;

		iifname "lo" accept

		ct state established,related accept

		iifname "br0" udp dport 53 accept
		iifname "br0" tcp dport 53 accept

		iifname "br0" udp sport 68 udp dport 67 accept
		iifname "wan" udp sport 67 udp dport 68 accept
		
		iifname "br0" tcp dport 80 accept
		iifname "br0" tcp dport 23 accept

		ip protocol icmp icmp type echo-request limit rate 10/second accept
	}

	chain forward {
		type filter hook forward priority 0; policy drop;
		
		ct state established,related ip protocol { tcp, udp } flow add @f
		ct state established,related accept

		iifname "br0" oifname "wan" accept
		iifname "br0.10" oifname "wan.10" accept
	}

	chain output {
		type filter hook output priority filter; policy accept;
	}
}
